package burp.utils;

import burp.BurpExtender;
import burp.api.montoya.MontoyaApi;
import burp.api.montoya.http.message.HttpRequestResponse;
import burp.api.montoya.scanner.audit.issues.AuditIssue;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.nio.file.Path;
import burp.utils.Utilities;

public class SourceMapper {
    private final MontoyaApi api;
    private final HttpRequestResponse requestResponse;
    private final String jsonMapFile;
    private final Path outputDirPath;

    public SourceMapper(HttpRequestResponse requestResponse, String jsonMapFile, Path outputDirPath) {
        this.api = Utilities.api;
        this.requestResponse = requestResponse;
        this.jsonMapFile = jsonMapFile;
        this.outputDirPath = outputDirPath;
        parseMapFile();
    }

    public void parseMapFile() {
        ObjectMapper objectMapper = new ObjectMapper()
                .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
        try {
            JSMapFile mapFile = objectMapper.readValue(jsonMapFile, JSMapFile.class);
            for (int i = 0; i <= mapFile.getSources().length - 1; i++) {
                if (FileUtils.saveFile(
                        mapFile.getSources()[i]
                                .replaceAll("\\?.*", "")
                                .replaceAll("[?%*|:\"<>~]", ""),
                        mapFile.getSourcesContent()[i].getBytes(),
                        outputDirPath
                )) {
                    sendJSMapperIssue();
                }
            }
        } catch (Exception e) {
            api.logging().logToError("Error processing the file - parseMapFile Exception: " + e.getMessage());
        }
    }

    private void sendJSMapperIssue() {
        try {
            AuditIssue issue = CustomScanIssue.from(
                    requestResponse,
                    "[JS Miner] JavaScript Source Mapper",
                    "This issue was generated by \"" + BurpExtender.EXTENSION_NAME + "\" Burp extension.<br><br>" +
                            "It was possible to retrieve JavaScript source map files of the target host." +
                            "The retrieved (front-end) source code is available (for manual review) in the following location:<br><br>"
                            + "<b>" + outputDirPath + "</b>",
                    null,
                    "Information",
                    "Certain"
            );
            api.siteMap().add(issue);
        } catch (Exception e) {
            api.logging().logToError("Error creating source mapper issue: " + e.getMessage());
        }
    }
}
